version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '18:00'
      timezone: 'Asia/Tokyo'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '18:00'
      timezone: 'Asia/Tokyo'
