name: deploy-weekly

on:
  schedule:
    - cron: '0 0 * * 1'

env:
  CI: true
  TZ: Asia/Tokyo

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm run build
      - run: npx vercel deploy --prod --no-clipboard --confirm --token=$TOKEN
        env:
          TOKEN: ${{ secrets.VERCEL_TOKEN }}
