name: pull-request
on: pull_request
env:
  CI: true
  TZ: Asia/Tokyo
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run lint
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.0
        with:
          node-version: '12.x'
      - run: npm ci
      - run: npm run build
